# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: GPL-3.0-or-later
version = 1
SPDX-PackageName = "Talk iOS App"
SPDX-PackageSupplier = "Nextcloud GmbH <https://nextcloud.com/impressum/>"
SPDX-PackageDownloadLocation = "https://github.com/nextcloud/talk-ios/"

[[annotations]]
path = [".gitmodules", "Podfile"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2017 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [".tx/config"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["NextcloudTalk/*.lproj/*.strings", "NextcloudTalk/*.lproj/*.stringsdict"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2020 Nextcloud translators"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = [".pyspelling.wordlist.txt"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ["ThirdParty/AppRTC/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2014-2017 The WebRTC Project Authors. All rights reserved."
SPDX-License-Identifier = "BSD-3-Clause"
