# SPDX-FileCopyrightText: 2023 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Check for localizable changes

on:
  push:
    branches:
      - main
      - master
      - stable*
  pull_request:
    branches:
      - main
      - master
      - stable*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-localizable:
    name: Check for localizable changes
    runs-on: macOS-15

    steps:
    - name: Checkout app
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
        submodules: true

    - name: Run localizable generation
      run: |
        source ./generate-localizable-strings-file.sh

    - name: Run git diff
      run: |
        git diff

    - name: Install dependencies
      run: |
        brew install aspell pyspelling

    - name: Spell check
      run: |
        pyspelling

    - name: Verify Changed files
      uses: tj-actions/verify-changed-files@6ed7632824d235029086612d4330d659005af687 # v20.0.1
      id: verify-changed-files
      if: always()
      with:
        fail-if-changed: true
        files: |
            NextcloudTalk/en.lproj/Localizable.strings
